import type { Metadata } from "next";
import { Inter, Bree_Serif, Young_Serif } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const bree_serif = Bree_Serif({ subsets: ["latin"], weight: "400" });
const young_Serif = Young_Serif({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={young_Serif.className}>{children}</body>
		</html>
	);
}
